apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.name}}
  description: vCluster for ${{values.name}}-${{values.stage}}
spec:
  type: kubernetes-cluster
  owner: ${{ values.owner }}
