apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: AppProject for all team applications
  sourceNamespaces:
  - "*"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - "*"
  destinations:
  - namespace: "*"
    server: "*"
