apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      - 052848974346.dkr.ecr.eu-central-1.amazonaws.com/backstage
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://backstage.github.io/charts'
    targetRevision: 1.6.1
    chart: backstage
    helm:
      valueFiles:
      - $values/gitops/management/backstage/backstage-values.yaml
  - repoURL: https://github.com/my-backstage-demo/backstage-infrastructure-provisioning-templates-workshop.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: "gitops/management/config"
    targetRevision: main
    directory:
      recurse: true
    repoURL: https://github.com/my-backstage-demo/backstage-infrastructure-provisioning-templates-workshop.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
