backstage:
  command: ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
  image:
    registry: 052848974346.dkr.ecr.eu-central-1.amazonaws.com
    repository: backstage
    pullPolicy: Always
  extraEnvVarsSecrets:
  - backstage-global-secrets
  extraEnvVars:
  - name: NODE_ENV
    value: development
