apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo-developmentb-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: dev
          team: developmentb
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: developmentb
      source:
        repoURL: https://stefanprodan.github.io/podinfo
        chart: podinfo
        targetRevision: 6.6.0
      destination:
        server: '{{server}}'
        namespace: podinfo
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
