apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 0.9.5
    chart: argocd-image-updater
  - repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 6.6.0
    chart: argo-cd
    helm:
      valueFiles:
      - $values/gitops/management/argocd/argocd-values.yaml
  - repoURL: https://github.com/my-backstage-demo/backstage-infrastructure-provisioning-templates-workshop.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
