apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-eks-cluster-dev-vc
  namespace: argocd
spec:
  destination:
    namespace: my-eks-cluster-dev
    server: https://kubernetes.default.svc
  project: clusters
  sources:
  - repoURL: 'https://charts.loft.sh/'
    targetRevision: 0.19.3
    chart: vcluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    #- ServerSideApply=true
    - CreateNamespace=true
