apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-backend-dev-developmentb
  namespace: argocd
spec:
  destination:
    namespace: my-backend-dev
    server: https://kubernetes.default.svc
  project: developmentb
  source:
    repoURL: 'https://charts.loft.sh/'
    targetRevision: 0.19.3
    chart: vcluster
    helm:
      values: |
        syncer:
          storage:
            persistence: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
