apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.owner | parseEntityRef | pick('name') }}-vcluster
  namespace: argocd
spec:
  destination:
    namespace: ${{values.stage}}-${{values.name}}
    server: https://kubernetes.default.svc
  project: cluster
  sources:
  - repoURL: 'https://charts.loft.sh/'
    targetRevision: 0.16.4
    chart: vcluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
