apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}-${{values.stage}}-${{ (values.owner | parseEntityRef).name }}
  namespace: argocd
spec:
  destination:
    namespace: ${{values.name}}-${{values.stage}}
    server: https://kubernetes.default.svc
  project: ${{ (values.owner | parseEntityRef).name }}
  source:
    repoURL: 'https://charts.loft.sh/'
    targetRevision: 0.20.0-beta.12
    chart: vcluster
    helm:
      values: |
        controlPlane:
          distro:
            k8s:
              enabled: true
          statefulSet:
            persistence:
              volumeClaim:
                enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
